enableImmutableInstalls: false

httpTimeout: 300000

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.6.0.cjs

# Skip problematic packages
packageExtensions:
  registry-js@*:
    dependencies:
      prebuild-install: "^7.0.0"

