name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["kind/bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
        Before submitting this issue, please make sure you have reviewed the [FAQ](https://github.com/TykoTech/TykoTech-Fork/wiki/FAQ) and [Knowledge Base](https://github.com/TykoTech/TykoTech-Fork/wiki)
  - type: checkboxes
    id: checklist
    attributes:
      label: Submission Checklist
      description: |
        Before submitting an issue, please ensure you have completed all of the following steps
      options:
        - label: I understand that Issues are for reporting and solving problems, not for complaints, and I will provide as much information as possible to help resolve the problem.
          required: true
        - label: My issue is not covered in the [FAQ](https://github.com/TykoTech/TykoTech-Fork/issues?q=is%3Aissue+label%3Afaq).
          required: true
        - label: I have reviewed the **pinned Issues** and searched through existing [open Issues](https://github.com/TykoTech/TykoTech-Fork/issues) and [closed Issues](https://github.com/TykoTech/TykoTech-Fork/issues?q=is%3Aissue+state%3Aclosed), and did not find any similar issues.
          required: true
        - label: I have entered a concise and clear title so that developers can quickly identify the issue when browsing the Issue list, rather than using vague titles like "A suggestion" or "Stuck", etc.
          required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of TykoTech Fork are you running?
      placeholder: e.g., v1.0.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please be as detailed as possible when describing the issue.
      placeholder: Clearly and concisely describe the bug you encountered.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can this issue be reproduced?
      placeholder: |
        1. Go to '...'
        2. Click '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Clearly and concisely describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Clearly and concisely describe the actual results.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: (If applicable) Add screenshots to help explain your problem.
      placeholder: You can drag and drop images here.
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other context about the problem here.
      placeholder: For example, system information, error logs, etc.
