name: 💡 Feature Request (Chinese)
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["kind/enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a feature request!
        Before submitting this issue, please make sure you have reviewed the [Project Roadmap](https://github.com/TykoTech/TykoTech-Fork/wiki/Roadmap) and the [Feature Overview](https://github.com/TykoTech/TykoTech-Fork/wiki/Features).
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: |
        Before submitting an Issue, please ensure you have completed all the following steps
      options:
        - label: I understand that Issues are for feedback and problem-solving, not for complaining in the comments section, and I will provide as much information as possible to help resolve the issue.
          required: true
        - label: I have checked the pinned Issues and searched existing [Open Issues](https://github.com/TykoTech/TykoTech-Fork/issues) and [Closed Issues](https://github.com/TykoTech/TykoTech-Fork/issues?q=is%3Aissue+state%3Aclosed), and no similar suggestion was found.
          required: true
        - label: I have filled in a short and clear title so that developers can quickly identify the general problem when browsing the Issue list, not "a suggestion," "stuck," etc.
          required: true
        - label: The latest version of TykoTech Fork does not include the feature I am suggesting.
          required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you using?
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of TykoTech Fork are you running?
      placeholder: e.g. v1.0.0
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
