name: ❓ Questions & Discussion (English)
description: Seeking help, discussing issues, asking questions, etc...
title: "[Discussion]: "
labels: ["kind/question"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your question! Please describe your issue in as much detail as possible so that we can better assist you.

  - type: checkboxes
    id: checklist
    attributes:
      label: Issue Checklist
      description: |
        Before submitting an Issue, please ensure you have completed all the following steps
      options:
        - label: I understand that Issues are for feedback and problem-solving, not for complaining in the comments section, and I will provide as much information as possible to help resolve the issue.
          required: true
        - label: I have checked the pinned Issues and searched existing [Open Issues](https://github.com/TykoTech/TykoTech-Fork/issues) and [Closed Issues](https://github.com/TykoTech/TykoTech-Fork/issues?q=is%3Aissue+state%3Aclosed), and no similar question was found.
          required: true
        - label: I confirm that I am here to ask questions and discuss issues, not to report bugs or request features.
          required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you using?
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of TykoTech Fork are you running?
      placeholder: e.g. v1.0.0
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe your question in detail.
      placeholder: Please state your question as clearly as possible...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your question.
      placeholder: You can drag and drop images here.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the question here.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this issue for you?
      options:
        - Low (Can look into it later)
        - Medium (Hope to get a reply soon)
        - High (Blocking work progress)
    validations:
      required: true
